project:
  type: book
  output-dir: docs
book:
  title: Compendio de pósteres de las 10° Jornadas Integradas, Año 2025
  subtitle: Facultad de Ciencias Agrarias | Universidad Nacional de Jujuy
  chapters:
  - index.qmd
  - autoridades.qmd
  - intro.qmd
  - cronograma.qmd
  - martes_16.qmd
  - jueves_18.qmd
  - miercoles_17.qmd
  - martes_23.qmd
  - resumen.qmd
  #- fca.qmd
  page-footer:
    center: FACULTAD DE CIENCIAS AGRARIAS - (Y4600DTA) - Alberdi N° 47 - S. S. de
      Jujuy - Jujuy – Argentina
    right: |
      ![](logofca.png){ width=80px }
      ![](logounju.png){ width=80px }
    left: Año 2025
  sidebar: 
    logo: integracion.gif
  downloads: [pdf]
bibliography: references.bib
lang: es
format:
  html:
    resources:
      - fondo.png
      - "*.mp3"
    embed-resources: true
    respect-user-color-scheme: true
    toc: true
    toc-location: right
    toc-depth: 2
    toc-title: En esta página
    fontsize: 0.9em
    css: estilos.css
  pdf:
    prefer-html: true
    documentclass: scrreprt
    keep-tex: true
editor: source
