project:
  type: book
  output-dir: docs
book:
  title: Libro de pósteres de las 10° Jornadas Integradas
  subtitle: Facultad de Ciencias Agrarias | Universidad Nacional de Jujuy
  chapters:
  - index.qmd
  - autoridades.qmd
  - intro.qmd
  - trabajos_estudiantes.qmd
  - trabajos_docentes.qmd
  - trabajos_egresados.qmd
  page-footer:
    center: FACULTAD DE CIENCIAS AGRARIAS - (Y4600DTA) - Alberdi N° 47 - S. S. de
      Jujuy - Jujuy – Argentina
    right: |
      ![](logofca.png){ width=80px }
      ![](logounju.png){ width=80px }
    left: Año 2025
bibliography: references.bib
lang: es
format:
  html:
    embed-resources: true
    standalone: true
    respect-user-color-scheme: true
    toc-title: En esta página
    fontsize: 0.9em
  pdf:
    documentclass: scrreprt
editor: source
