# Cronograma

::: {.callout-note .verde collapse=true icon=false}
## Martes 16
- USO DE ASERRÍN Y COMPOST COMO SUSTRATOS ALTERNATIVOS EN LA PRODUCCIÓN DE PLANTINES DE ENTEROLOBIUM CONTORTISILIQUUM “PACARA” EN LA PROVINCIA DE JUJUY

- PERFIL PALINOLÓGICO Y NUTRICIONAL DEL POLEN APÍCOLA COSECHADO DURANTE LA CAMPAÑA 2024/2025 EN SAN PEDRO JUJUY (ARGENTINA)

- EVALUACIÓN MICROBIOLÓGICA DE LECHUGA (Lactuca sativa L.) PRODUCIDA EN HUERTAS ESCOLARES DEL DPTO. DR. MANUEL BELGRANO

- MODELADO DE PRECIOS MINORISTAS DE HORTALIZAS EN JUJUY: UN ENFOQUE BASADO EN MECANISMOS DE TRANSMISIÓN DE PRECIOS CON VECM

- PROMOCIÓN DE PRÁCTICAS SUSTENTABLES EN SISTEMAS HORTÍCOLAS: EXTRACTOS VEGETALES CON CAPACIDAD BIOENRAIZANTE, BIOFERTILIZANTE Y BIOPROTECTORA

- HUERTA AGROECOLOGICA ESCOLAR: EL HUERTO DE COLORES

- EDUCACIÓN ALIMENTARIA EN LA FORMACIÓN DEL LICENCIADO EN BROMATOLOGÍA: EXPERIENCIAS DE CAPACITACIÓN EN CONTEXTOS REALES


:::

::: {.callout-note .verdeoscuro collapse=true icon=false}
## Miércoles 17
- ESTUDIOS PRELIMINARES SOBRE LA PRESENCIA DE BACTERIAS DEL GÉNERO Pseudomonas spp. EN RÍOS DE LA QUEBRADA DE HUMAHUACA, DURANTE ÉPOCA LLUVIOSA

- DINÁMICA DE LA RESTAURACIÓN PASIVA, A PARTIR DE LA REGENERACIÓN, EN UN BOSQUE DISTURBADO DE LA SELVA PEDEMONTANA DE YUNGAS

- EL PODCAST Y LA RADIO EN VIVO COMO HERRAMIENTAS PEDAGÓGICAS PARA GESTIÓN AMBIENTAL

- ESTIMACIÓN DE ÍNDICES DE PRECIOS MAYORISTAS DE LAS PRINCIPALES FRUTAS Y HORTALIZAS RELEVADAS EN EL MERCADO FORMADOR DE PRECIOS DE LA REGIÓN DEL NOA ARGENTINO

- TENDIENDO PUENTES ENTRE UNIVERSIDAD Y COMUNIDAD - PROYECTO “CRECE JUNTO A TU ÁRBOL”, VOLUNTARIADO UNIVERSITARIO

- MANITAS LIMPIAS SALVAN VIDAS

- FACTORES QUE INFLUYEN EN LAS DIFICULTADES DE APRENDIZAJE EN QUÍMICA GENERAL: PERCEPCIONES DE ESTUDIANTES DE BROMATOLOGÍA


:::

::: {.callout-note .amarillo collapse=true icon=false}
## Jueves 18
- IMPLEMENTACIÓN DEL APRENDIZAJE BASADO EN PROYECTOS EN LAS ASIGNATURAS BIOESTADÍSTICA (LICENCIATURA EN CIENCIAS BIOLÓGICAS) Y ESTADÍSTICA (LICENCIATURA EN DESARROLLO RURAL) DE LA UNJU

- COMPOSICIÓN QUÍMICA DE ACEITES ESENCIALES DE ROMERO (Rosmarinus officinalis) Y TOMILLO (Thymus vulgaris). ESTUDIO DE SUS PROPIEDADES ANTIMICROBIANAS FRENTE A BACTERIAS GRAM NEGATIVAS

- CARACTERIZACIÓN FISICOQUÍMICA DE PELÍCULAS COMESTIBLES A BASE DE ALMIDÓN DE PAPA Y ÁCIDO CÍTRICO COMO ADITIVO

- EVALUACIÓN DE PRÁCTICAS DEL USO DE SAL Y CONOCIMIENTOS EN PANADERÍAS DE LA PROVINCIA DE JUJUY

- CONTROL DE CALIDAD EN FRUTOS DE POMELO (Citrus paradisi): EVALUACIÓN DE LA CAPACIDAD DEL PROCESO EN PRECOSECHA

- EVALUACIÓN IN VIVO DE EXTRACTOS DE PROPÓLEOS FRENTE A NOSEMA SP. EN APIS MELLIFERA DE LA PROVINCIA DE JUJUY

- ICTIOFAUNA DEL RÍO XIBI-XIBI (JUJUY): UNA APROXIMACIÓN AL CONOCIMIENTO DE SU DIVERSIDAD Y DISTRIBUCIÓN

- EVALUACIÓN DEL EFECTO CITOTOXICO DE MUÑA MUÑA (CLINOPODIUM GILLIESII) SOBRE GORGOJOS DEL POROTO (ACANTHOSCELIDES OBTECTUS)

:::

::: {.callout-note .rojo collapse=true icon=false}
## Martes 23
- REGULACIÓN ALIMENTARIA Y PERCEPCIONES EN FERIAS POPULARES DE JUJUY

- DIVERSIDAD ENDOFÍTICA DE TECOMA STANS (GUARÁN-GUARÁN) EN JUJUY

- HERRAMIENTAS PARA LA GESTIÓN SUSTENTABLE DEL ARBOLADO URBANO - METÁN, SALTA

- PRÁCTICAS AGROECOLÓGICAS DE CONTROL SANITARIO EN EL CULTIVO DE PAPA (SOLANUM TUBEROSUM VAR. SPUNTA) EN LA ESCUELA PROVINCIAL AGROTECNCIA N°1 EL BRETE-PALPALA

- FACTORES QUE INCIDEN EN LA DESERCIÓN Y REPROBACIÓN DE LOS ESTUDIANTES EN LA MATERIA DE ÁLGEBRA Y GEOMETRÍA ANALÍTICA EN LA FACULTAD DE CIENCIAS AGRARIAS.

- CARACTERIZACIÓN MORFOLÓGICA Y FÍSICA DE ACCESIONES CRIOLLAS DE HABAS (VICIA FABA L.)

- EVALUACIÓN DE DIFERENTES INDICADORES DE CALIDAD DE GRANO EN UN GENOTIPO DE SOJA (GLYCINE MAX (L) CULTIVADO EN AMBIENTES CONTRASTANTES

- ESPOROFITOS DE DOS ESPECIES DEL COMPLEJO ASPLENIUM SERRA (ASPLENIACEAE) DE LAS YUNGAS ARGENTINAS, MEDIANTE LA APLICACION DE TECNICAS DE LABORATORIO CONVENCIONALES.

:::



