# Objetivos de las Jornadas

## Objetivo general

Informar y difundir las actividades de docencia, investigación y extensión llevadas a cabo por las diversas carreras de esta Facultad, destinadas a la comunidad universitaria, entidades oficiales, privadas o interesadas en las actividades que se desarrollan en esta unidad académica. Así mismo, se busca incentivar a los estudiantes de la Facultad de Ciencias Agrarias a la participación en eventos de carácter formativo y en la socialización de conocimientos adquiridos, además de ser un espacio para dar a conocer la oferta académica de la FCA.

## Objetivos particulares

Fortalecer los vínculos existentes entre Docencia, Investigación y Extensión a los fines de integrar y articular grupos interdisciplinarios.

Consolidar las relaciones existentes entre el medio local, regional y la Facultad.

Generar un espacio participativo de intercambio y articulación entre los diferentes actores.

Incentivar y desarrollar aptitudes para la comunicación oral y escrita de experiencias académicas, de extensión e investigación (Horas de Campo, Prácticas Profesionales, Pasantías con Trabajo Final, etc.).

Propiciar una mayor inserción de la Facultad en el medio para abordar problemáticas de interés de la comunidad.

Posicionar a la Facultad como órgano de referencia en las Áreas de Extensión y Educación.

Brindar capacitaciones a la comunidad educativa y a los que deseen participar.

